### ISSUE TITLE
Raylib Simple Project doesn't build on Mac M1

### ISSUE THREAD

**Issue by JudgeGroovyman** [GuvaCode/ray4laz#31]
# Summary
I'm on an M1 Macbook Air with OS Sonoma 14.5 and I get the attached error log when I open a `new raylib simple project` and hit build.  I didn't change the code at all.

# Build Logs
I tried installing ray4laz twice in two different ways and got the same basic log both times.

## Installed using fpcupdeluxe installer
Here is the build log with errors from the new raylib simple project when I installed ray4laz using the fpcupdeluxe installer::
[raylib simple project errors from fpcupdeluxe install.txt](https://github.com/user-attachments/files/17381698/raylib.simple.project.errors.from.fpcupdeluxe.install.txt)

## Installed manually using .lpk files
Here is the build log with errors from the new raylib simple project when  I installed ray4laz manually using the .lpk files
[raylib simple project errors from manual install.txt](https://github.com/user-attachments/files/17381688/raylib.simple.project.errors.from.manual.install.txt)

## Summary of the error

``` 
Undefined symbols for architecture arm64:
  "_BeginDrawing", referenced from:
      _PASCALMAIN in game.o
  "_ClearBackground", referenced from:
      _PASCALMAIN in game.o
  "_CloseWindow", referenced from:
      _PASCALMAIN in game.o
  "_DrawText", referenced from:
      _PASCALMAIN in game.o
  "_EndDrawing", referenced from:
      _PASCALMAIN in game.o
  "_GetScreenToWorldRay", referenced from:
      _RAYLIB_$$_GETMOUSERAY$TVECTOR2$TCAMERA3D$$TRAY in raylib.o
  "_InitWindow", referenced from:
      _PASCALMAIN in game.o
  "_SetTargetFPS", referenced from:
      _PASCALMAIN in game.o
  "_WindowShouldClose", referenced from:
      _PASCALMAIN in game.o
ld: symbol(s) not found for architecture arm64
```

## Installation Output with ld warnings:
Here is the installation output from fpcupdeluxe:
[Ray4LazInstallLogFromFPCUpDeluxe.txt](https://github.com/user-attachments/files/17381687/Ray4LazInstallLogFromFPCUpDeluxe.txt)

### Short answer: I tried but couldn't.
For background I initially tried using the "online package manager" as mentioned in the screenshots however there were enormous lazarus based build problems on M1 mac and after hours of attempts I got it all compiled using this build tool called [fpcupdeluxe](https://github.com/LongDirtyAnimAlf/fpcupdeluxe).  However that build tool builds it without the online package manager unfortunately.  

# Finally
I wish I could figure this out on my own but I couldn't do it.  But hmu if I can help test things or if you have anything I should try to get it working.  I would like to help figure it out. :)

**Comment by GuvaCode** [comment]
Good. I understand your problem. 
There are no compiled libraries for the arm architecture. I'll try to add support tomorrow.
Your help will be needed for testing

**Comment by GuvaCode** [comment]
Unfortunately, the task of cross-compilation turned out to be very difficult for me.

But you can try to compile the library yourself.


# Without Xcode - Building Statically 

Building statically means you can run this application on other machines with ease - users won't have to have any of the frameworks installed that are required. Also, this will work on mac's 10.9 and up.

## Here's the quick instructions:

1. From the command line 
```
export MACOSX_DEPLOYMENT_TARGET=10.9
```
2. Install XCode tools (don't forget to then update the tools in the Mac App Store after!)
````
xcode-select --install
````
3. Build raylib (Again, this is so the export line takes effect) 

````
git clone https://github.com/raysan5/raylib.git
cd raylib/src
make
````

You may do the otool check with the file in raylib/src/libraylib.a here if you like. (LC_VERSION_MIN_MACOSX should be version 10.4), and we're good!
```
copy file libraylib.a to Ray4Laz/libs/aarch64-macos <--- I'm not sure if the folder should be named that way for the mac m1 architecture.
```

**Comment by JudgeGroovyman** [comment]
Ok I'm on it!

**Comment by JudgeGroovyman** [comment]
Here is the new Libs and Packages folders along with a similar error log to before.

To be sure: I am just starting a new simple project and hitting compile.  Is that correct?  That should work right?


```
Hint: (11030) Start of reading config file /etc/fpc.cfg
Hint: (11031) End of reading config file /etc/fpc.cfg
Free Pascal Compiler version 3.2.2 [2021/05/16] for aarch64
Copyright (c) 1993-2021 by Florian Klaempfl and others
(1002) Target OS: Darwin for AArch64
(3104) Compiling /Users/johnmcgarey/tmp/game.lpr
(9009) Assembling game
(9015) Linking /Users/johnmcgarey/tmp/game
ld: warning: -multiply_defined is obsolete
-macosx_version_min has been renamed to -macos_version_min
Undefined symbols for architecture arm64:
  "_BeginDrawing", referenced from:
      _PASCALMAIN in game.o
  "_ClearBackground", referenced from:
      _PASCALMAIN in game.o
  "_CloseWindow", referenced from:
      _PASCALMAIN in game.o
  "_DrawText", referenced from:
      _PASCALMAIN in game.o
  "_EndDrawing", referenced from:
      _PASCALMAIN in game.o
  "_GetScreenToWorldRay", referenced from:
      _RAYLIB_$$_GETMOUSERAY$TVECTOR2$TCAMERA3D$$TRAY in raylib.o
  "_InitWindow", referenced from:
      _PASCALMAIN in game.o
  "_SetTargetFPS", referenced from:
      _PASCALMAIN in game.o
  "_WindowShouldClose", referenced from:
      _PASCALMAIN in game.o
ld: symbol(s) not found for architecture arm64
An error occurred while linking 
Error: (9013) Error while linking
Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/local/bin/ppca64 returned an error exitcode
```

**Comment by GuvaCode** [comment]
Are you uploading as a static library? 

Add to raylib.inc

{$IFDEF DARWIN}
  {$DEFINE RAY_STATIC}
{$IFEND}

**Comment by JudgeGroovyman** [comment]
Thanks for the ideas!  I made a .a file before. Ill try to make a dynamic library just like you described.  I have to admit to being just barely above water in terms of my abilities but I am learning a lot :)

**Comment by JudgeGroovyman** [comment]
Update: I built a dylib like you suggested and copied it into the ray4laz folder and then edited the raylib.inc as suggested and compiled ray4laz and then compiled and installed ray4lazdesigntime and _got the same errors_.  Here are the Libs and Package folders 
[Ray4Laz Libs and Package folders with error logs.zip](https://github.com/user-attachments/files/17438619/Ray4Laz.Libs.and.Package.folders.with.error.logs.zip)

I'm starting to wonder if my process is correct.  I've been compiling and installing the packages from `Package->Open Package File (.lpk)` it then says 
```Rebuild Lazarus?
The package "ray4laz_designtime 5.5" was marked for installation.
Currently Lazarus only supports static linked packages. The real installation needs rebuilding and restarting of Lazarus.
Do you want to rebuild Lazarus now?
``` and I click yes.

What is your process for compiling and installing the packages?

**Comment by JudgeGroovyman** [comment]
> there may not be enough libraries for static linking
> 
> you can try to rewrite this one for mac os
> 
> implementation uses Math;
> 
> {$IFDEF linux} {$IFDEF RAY_STATIC} {$linklib c} {$linklib m} {$linklib dl} {$linklib pthread} {$linklib libraylib.a} {$endif} {$endif}

For this I'm kind of lost, does this mean putting this code in a new file and putting it in the build path somewhere?

**Comment by GuvaCode** [comment]
No need if you use a dynamic library. And os x will most likely need other libraries for the static version. This is just an example

**Comment by JudgeGroovyman** [comment]
I still get these errors but I got these clues:
1. I get the same errors if I go into the examples and try building the basic_window from the command line with fpc.  
2. I used nm to verify that those symbols were in the .a and the .dylib 
3. I used `lipo -info` to verify that the architecture of both was 'arm64'  
4. I even got the same errors in a totally different project [Raylib4.0Pascal](https://github.com/sysrpl/Raylib.4.0.Pascal) when I tried compiling with fpc from the command line.  

Here are the errors:
```Undefined symbols for architecture arm64:
  "_BeginDrawing", referenced from:
      _PASCALMAIN in game.o
  "_ClearBackground", referenced from:
      _PASCALMAIN in game.o
  "_CloseWindow", referenced from:
      _PASCALMAIN in game.o
  "_DrawText", referenced from:
      _PASCALMAIN in game.o
  "_EndDrawing", referenced from:
      _PASCALMAIN in game.o
  "_GetScreenToWorldRay", referenced from:
      _RAYLIB_$$_GETMOUSERAY$TVECTOR2$TCAMERA3D$$TRAY in raylib.o
  "_InitWindow", referenced from:
      _PASCALMAIN in game.o
  "_SetTargetFPS", referenced from:
      _PASCALMAIN in game.o
  "_WindowShouldClose", referenced from:
      _PASCALMAIN in game.o
```

What should I try next?

**Comment by GuvaCode** [comment]
> I have the same problem on my MacOS Mojave (x86_64-darwin) and I think I've managed to solve it. I'm using latest (with fixes) Lazarus FPCUPdeluxe build.
> 
> These are the steps for a static build:
> 
>     1. Clone Ray4Laz and RayLib repositories
> 
>     2. Compile RayLib with:
>        `make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED`
>        `make PLATFORM=PLATFORM_DESKTOP`
> 
>     3. Copy:
>        libraylib.5.5.0.dylib, libraylib.550.dylib, libraylib.a, libraylib.dylib –> path_to/ray4laz/libs/x86_64-darwin
> 
>     4. Compile `ray4laz.lpk`
> 
>     5. Compile and install `ray4laz_designtime.lpk`
> 
>     6. Add `{$LINKLIB raylib.a}` into your_project.lpr file (right after `{$mode objfpc}{$H+}`)
> 
>     7. Add `CocoaAll` unit into your_project.lpr `uses`
> 
>     8. Project–>Project Options–>Compiler Options–>Compilation and Linking–>Linking–>Pass options to linker... :
>        add `'-framework IOKit'` – with quotes!
> 
>     9. Build your project...
> 
> 
> If on step 6 you specify `{$LINKLIB raylib}` (without `.a`), then it will use dynamic library. But in this case you have to tell your app where are RayLib compiled library files located. Otherwise you'll not be able to run your app. I've simply added: Run–>Run Parameters...–>Environment–>User overrides, variable `LD_LIBRARY_PATH` where value is the path to the directory with RayLib *.dylib files.
> 
> I hope I didn't forget anything.
> 
> PS. You have to replace `x86_64-darwin` with `aarch64-darwin`. PPS. I didn't test raygui, raymath... Also, one of the remaining tasks is to create the .app bundle in case of dynamic linking, or if the project has any assets.

**Vlad, thank you very much for the work you have done.** 
Following your instructions, I changed the package. 
Could you test the latest changes. 

You only need to use step 3.

**Comment by vvladonline** [comment]
I've tested last commit, but there is 2 problems.
1. In step 8 there is a check box, that needs to be checked for `'-framework IOKit'` to work
`Pass options to linker with "-k", delimiter is space`
3. In `raylib.inc` file you have to remove dot in `{.$DEFINE RAY_STATIC}` directive ([raylib.inc.patch](https://github.com/user-attachments/files/17560400/raylib.inc.patch))

After that, build and run will be succeed.

**Comment by JudgeGroovyman** [comment]
> 2. Compile RayLib with:
>    `make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED`
>    `make PLATFORM=PLATFORM_DESKTOP`

@GuvaCode here are the arm64 .a and .dylib files that I just built from Raylib master (I confirmed with lipo -info they are arm64)
[aarch64-darwin.zip](https://github.com/user-attachments/files/17560785/aarch64-darwin.zip)

**Comment by GuvaCode** [comment]
> > 2. Compile RayLib with:
> >    `make PLATFORM=PLATFORM_DESKTOP RAYLIB_LIBTYPE=SHARED`
> >    `make PLATFORM=PLATFORM_DESKTOP`
> 
> @GuvaCode here are the arm64 .a and .dylib files that I just built from Raylib master (I confirmed with lipo -info they are arm64) [aarch64-darwin.zip](https://github.com/user-attachments/files/17560785/aarch64-darwin.zip)

Did you manage to launch it? Is everything working?

**Comment by vvladonline** [comment]
I can confirm that after reinstalling Ray4Laz from the last commit, new `raylib simple project` builds and runs perfectly.
Thank you!

**Comment by JudgeGroovyman** [comment]
95% there!  Thanks to both of you @vvladonline  and @GuvaCode for helping me make so much progress.

The only one remaining is:

```
Error: linker: Undefined symbols for architecture arm64:
Error: linker:   "___chkstk_darwin", referenced from:
Debug:   "___chkstk_darwin", referenced from:
Debug:       _msf_gif_frame in libraylib.a[2](rcore.o)
Debug:       _sinfl_decompress in libraylib.a[2](rcore.o)
Debug:       _ScanDirectoryFilesRecursively in libraylib.a[2](rcore.o)
Debug:       _stbi_load_gif_from_memory in libraylib.a[4](rtextures.o)
Debug:       _stbi_zlib_decode_malloc_guesssize in libraylib.a[4](rtextures.o)
Debug:       _stbi_zlib_decode_malloc in libraylib.a[4](rtextures.o)
Debug:       _stbi_zlib_decode_malloc_guesssize_headerflag in libraylib.a[4](rtextures.o)
Debug:       ...
Error: ld: symbol(s) not found for architecture arm64
```

**Comment by GuvaCode** [comment]
> 95% there! Thanks to both of you @vvladonline and @GuvaCode for helping me make so much progress.
> 
> The only one remaining is:
> 
> ```
> Error: linker: Undefined symbols for architecture arm64:
> Error: linker:   "___chkstk_darwin", referenced from:
> Debug:   "___chkstk_darwin", referenced from:
> Debug:       _msf_gif_frame in libraylib.a[2](rcore.o)
> Debug:       _sinfl_decompress in libraylib.a[2](rcore.o)
> Debug:       _ScanDirectoryFilesRecursively in libraylib.a[2](rcore.o)
> Debug:       _stbi_load_gif_from_memory in libraylib.a[4](rtextures.o)
> Debug:       _stbi_zlib_decode_malloc_guesssize in libraylib.a[4](rtextures.o)
> Debug:       _stbi_zlib_decode_malloc in libraylib.a[4](rtextures.o)
> Debug:       _stbi_zlib_decode_malloc_guesssize_headerflag in libraylib.a[4](rtextures.o)
> Debug:       ...
> Error: ld: symbol(s) not found for architecture arm64
> ```
> 
> Here is the full log in case that helps anyone [Just one linker error now.txt](https://github.com/user-attachments/files/17561333/Just.one.linker.error.now.txt)

**Error: -macosx_version_min has been renamed to -macos_version_min**
export MACOSX_DEPLOYMENT_TARGET=11.0 _but most likely you need 14.5_

in folder raylib/src --> make clean 
rebuild raylib

**Comment by GuvaCode** [comment]
> I can confirm that after reinstalling Ray4Laz from the last commit, new `raylib simple project` builds and runs perfectly.
> Thank you!

I deployed the VM and compiled with raygui nested
Could you check it out? I'm not sure it's going to work at all.

**Comment by vvladonline** [comment]
> I deployed the VM and compiled with raygui nested
> Could you check it out? I'm not sure it's going to work at all.

Yes, it's works. I've reinstalled Ray4Laz and build&run simple project.
But i'm not sure if all these files are needed. I removed `libraylib.550.dylib` and `libraylib.dylib` symlinks, renamed `libraylib.5.5.0.dylib` to `libraylib.dylib` and the project still builds and runs fine. I left `libraylib.a` as is.

**Comment by GuvaCode** [comment]
> > I deployed the VM and compiled with raygui nested
> > Could you check it out? I'm not sure it's going to work at all.
> 
> Yes, it's works. I've reinstalled Ray4Laz and build&run simple project. But i'm not sure if all these files are needed. I removed `libraylib.550.dylib` and `libraylib.dylib` symlinks, renamed `libraylib.5.5.0.dylib` to `libraylib.dylib` and the project still builds and runs fine. I left `libraylib.a` as is.

Thank you. Yes, symbolic links are not needed.

**Comment by JudgeGroovyman** [comment]
> export MACOSX_DEPLOYMENT_TARGET=11.0 _but most likely you need 14.5_
> 
> in folder raylib/src --> make clean rebuild raylib

I did make clean and then rebuilt raylib then copied the files over and rebuilt my project in lazarus.  I tried it with several deployment targets and got almost the same errors as the errors above each time. 

[MACOSX_DEPLOYMENT_TARGET10.9.txt](https://github.com/user-attachments/files/17562074/MACOSX_DEPLOYMENT_TARGET10.9.txt)
[MACOSX_DEPLOYMENT_TARGET11.0.txt](https://github.com/user-attachments/files/17562075/MACOSX_DEPLOYMENT_TARGET11.0.txt)
[MACOSX_DEPLOYMENT_TARGET14.5.txt](https://github.com/user-attachments/files/17562076/MACOSX_DEPLOYMENT_TARGET14.5.txt)



Now I'm looking into what to do about 
> **Error: -macosx_version_min has been renamed to -macos_version_min**

**Comment by JudgeGroovyman** [comment]
### Big Progress via manual edits
> **Error: -macosx_version_min has been renamed to -macos_version_min** 

I went into the project folder and manually changed the latest `link35561.res` from `macosx_version_min` to `macos_version_min` and then changed the version to 11.0 and manually ran `./ppaslink.sh` and it built and I could run it!  Thats the first time it has worked for me! 
![Screenshot 2024-10-29 at 3 06 31 PM](https://github.com/user-attachments/assets/598d7b36-5584-4b53-adf5-9e69eaf93fae)

I'm going to try to reproduce that and see if it works again.

**Comment by GuvaCode** [comment]
@JudgeGroovyman I have changed the project options for arm 
https://forum.lazarus.freepascal.org/index.php?topic=43188.0

Can I watch this
https://gitlab.kitware.com/cmake/cmake/-/issues/25530

**Comment by vvladonline** [comment]
@JudgeGroovyman You also can search in your `fpc.cfg` (local or global) file for `-WM` option. In my `fpc.cfg` I have -WM10.9

**Comment by JudgeGroovyman** [comment]
> please attach the files libraylib on which you are running
First of all here are the libraries i'm running that worked
[LibsforMacM1Works.zip](https://github.com/user-attachments/files/17590555/LibsforMacM1Works.zip)

> @JudgeGroovyman I have changed the project options for arm 
> 
> please test it simple project
Sure I will go test

**Comment by JudgeGroovyman** [comment]
### Success!
Change `-WM11` to `-WM11.0` in `ray4laz/package/ray4laz_simpleprj.pas` and it works!  

### Details of what I did
#### Before I figured out the problem 
I changed my fpc.cfg from `-WM10.9` to `-WM11` and Lazarus wouldn't even start.  I changed it to `-WM11.0` and Lazarus started.  I copying my arm64 libs over to the ray4laz/libs/aarch64-darwin folder.  Then I compiled and imported the ray4laz packages into lazarus, then opened a new->raylib-simple-project and saved and compiled it.  It didn't build and said `Error: Illegal parameter: -WM11` so I went and double checked my fpc.config and tried various things and (because I didn't know better) even rebuilt fpc and lazarus and it still didn't work.  

#### Finding the solution
Then I did some grepping and found the problem in the .lpi and fixed it and it worked.  
Finally I went into the ray4laz repo and found `-WM11` in the /package/ray4laz_simpleprj.pas and changed it there, recompiled the packages, reimported, started a new simple project and it built and ran the first time!

**Comment by GuvaCode** [comment]
@JudgeGroovyman  @vvladonline  Thanks. Great job !!!

**Comment by JudgeGroovyman** [comment]
@GuvaCode to run the examples I have to do 2 small tweaks to each example project folder: 
1. add `CocoaAll` to the uses section of the .lpr or the .pas
2. Near the end of the Linking section of the .lpi file  Replace
```
   </Linking>
  </CompilerOptions>
```
with
```
      <Options>
        <PassLinkerOptions Value="True"/>
        <LinkerOptions Value="&apos;-framework IOKit&apos;"/>
      </Options>
    </Linking>
    <Other>
      <CustomOptions Value="&apos;-WM11.0&apos;"/>
    </Other>
  </CompilerOptions>
```


What would you like to do about these?  I could make a similar change to all of the examples, or I could make a note in the readme about these tweaks or something else?

lmk how I can help

**Comment by GuvaCode** [comment]
@JudgeGroovyman Good. But you will probably need to create a separate folder with examples for the Mac M series. I'm not sure if the changes won't break compilation for other systems.

**Comment by JudgeGroovyman** [comment]
> @JudgeGroovyman Good. But you will probably need to create a separate folder with examples for the Mac M series. I'm not sure if the changes won't break compilation for other systems.

Good plan I'll make a separate folder and fix those examples.

**Comment by JudgeGroovyman** [comment]
Here is the separate folder with examples for Mac M series.  it has a detailed readme (in markdown) in that folder.
[examples_Mac_Mseries.zip](https://github.com/user-attachments/files/17639055/examples_Mac_Mseries.zip)

###  Option 2
Another option I thought of if you would prefer: I could send a script which lets mac m1 users modify their own examples folder.  This way there wouldn't be multiple folders.  I would include the detailed readme with the script as well.  otoh it would be a bit more complicated and potentially its one more thing that could break.  

### Option 3
We could just include the detailed readme and Mac Mseries users could modify their own examples.  It's very easy when you know what to do and just one copy/pasted command can fix the whole examples tree.  

Let me know if you want me to whip something up for Option 2 or 3 otherwise the zipfile at the top should do the trick and has the readme built in

**Comment by GuvaCode** [comment]
@JudgeGroovyman Well, I think option 3 would be interesting. you need something to make it clear how to use it.

**Comment by JudgeGroovyman** [comment]
This is the readme I wrote which I think has plenty of detail.  If you like that then roll with it.  Would this work?

Here is the actual markdown file to be included in the repo
[README_Mac_Mseries.md](https://github.com/user-attachments/files/17639854/README_Mac_Mseries.md)
Here is roughly what it looks like when rendered in the github interface.  
[README_Mac_Mseries.md.pdf](https://github.com/user-attachments/files/17639856/README_Mac_Mseries.md.pdf)

You could link to the .md from the main README.md if you wanted.

**Comment by GuvaCode** [comment]
@JudgeGroovyman OK. I'll turn it on. but it is better to send pull requests to include you in the contributors of the project

**Comment by JudgeGroovyman** [comment]
Thank you.  Good idea.   If its not too late I will do a pr.  lmk

**Comment by GuvaCode** [comment]
Ok

**Comment by vvladonline** [comment]
> **When creating a new project, this was added a few days ago**
> 
> ```pascal
>  {$IFDEF DARWIN}
>    Aproject.LazCompilerOptions.PassLinkerOptions := True;
>  {$IFDEF CPUAARCH64}
>    AProject.LazCompilerOptions.CustomOptions:='''-WM11.0''';
>  {$ENDIF}
>    AProject.LazCompilerOptions.LinkerOptions := '''-framework IOKit''';
>  {$ENDIF}
>  AProject.AddPackageDependency('ray4laz');
> ```

Yes, i know that. But the last discussion was about examples.
Changing .lpi files may looks for some people a little hackish. So perhaps changes through the user interface would be more acceptable.
Or examples .lpi files can be changed in repository with "Conditionals" that i've mention.

PS. I can not test solutions for aarch64, so i think @JudgeGroovyman may help with that.

**Comment by GuvaCode** [comment]
@vvladonline Yes, I thought about this approach. But I have no way to verify this.

Maybe @JudgeGroovyman he can check it out

**Comment by GuvaCode** [comment]
@vvladonline @JudgeGroovyman  I have created a new issued, it is already too big
[Example build for mac M series](https://github.com/GuvaCode/ray4laz/issues/33#issue-2640991274)
